name: Build PS2 Game

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          apk update && apk add make

      - name: Compile ELF
        run: |
          make clean
          make

      - name: Upload Finished Game
        uses: actions/upload-artifact@v4
        with:
          name: PS2-Game-Executable
          path: my_ps2_game.elf
